channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - beautifulsoup4=4.6.0
  - blas=1.0
  - bleach=1.4.2
  - bokeh=0.12.13
  - bottleneck=1.2.1
  - bz2file=0.98
  - ca-certificates=2019.3.9
  - cachecontrol=0.12.5
  - cachetools=2.1.0
  - cairo=1.14.10
  - certifi=2019.3.9
  - cffi=1.11.5
  - chardet=3.0.4
  - clangdev=5.0.0
  - click=6.7
  - cloudpickle=0.5.2
  - contextlib2=0.5.5
  - cryptography=2.5
  - curl=7.62.0
  - cycler=0.10.0
  - dask=0.17.1
  - dask-core=0.17.1
  - defusedxml=0.5.0
  - distributed=1.21.1
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - fontconfig=2.12.6
  - freetype=2.8.1
  - future=0.17.1
  - gettext=0.19.8.1
  - glib=2.55.0
  - gmp=6.1.2
  - google-api-python-client=1.7.8
  - google-auth=1.6.3
  - google-auth-httplib2=0.0.3
  - gseapy=0.8.11
  - h5netcdf=0.5.0
  - h5py=2.7.1
  - hdbscan=0.8.12
  - hdf4=4.2.13
  - hdf5=1.10.1
  - heapdict=1.0.0
  - html5lib=1.0.1
  - httplib2=0.12.1
  - icu=58.2
  - idna=2.6
  - igraph=0.7.1
  - imbalanced-learn=0.4.2
  - intel-openmp=2018.0.0
  - ipykernel=4.7.0
  - ipython=6.2.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.1.0
  - jdcal=1.3
  - jedi=0.10.2
  - jinja2=2.10
  - joblib=0.12.5
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_console=5.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.4.0
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.1.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.0
  - jupyterlab=0.31.8
  - jupyterlab_launcher=0.10.5
  - keras=2.1.5
  - kiwisolver=1.0.1
  - krb5=1.14.2
  - libcurl=7.62.0
  - libffi=3.2.1
  - libiconv=1.15
  - libnetcdf=4.5.0
  - libpng=1.6.34
  - libprotobuf=3.5.2
  - libsodium=1.0.15
  - libssh2=1.8.0
  - libxml2=2.9.7
  - libxslt=1.1.32
  - llvm-meta=5.0.0
  - llvmdev=5.0.0
  - locket=0.2.0
  - lockfile=0.12.2
  - loompy=2.0.3
  - louvain=0.6.1
  - lxml=4.1.1
  - markupsafe=1.0
  - matplotlib-venn=0.11.5
  - mistune=0.8.3
  - mkl=2019.0
  - mock=2.0.0
  - msgpack-python=0.5.5
  - natsort=6.0.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf4=1.3.1
  - nose=1.3.7
  - numpy=1.12.1
  - openpyxl=2.4.0
  - openssl=1.1.1b
  - pandas=0.22.0
  - pandoc=2.1
  - pandocfilters=1.4.1
  - partd=0.3.8
  - patsy=0.5.0
  - pbr=4.0.2
  - pcre=8.39
  - pexpect=4.3.1
  - pickleshare=0.7.4
  - pip=9.0.1
  - pixman=0.34.0
  - prompt_toolkit=1.0.15
  - protobuf=3.5.2
  - psutil=5.4.0
  - ptyprocess=0.5.2
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.4
  - pycairo=1.13.3
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pysocks=1.6.8
  - python=3.6.7
  - python-dateutil=2.6.1
  - python-igraph=0.7.1.post6
  - pytz=2018.3
  - pyyaml=3.12
  - qt=5.6.2
  - qtconsole=4.3.1
  - readline=7.0
  - requests=2.18.4
  - rsa=3.4.2
  - scikit-bio=0.4.2
  - scikit-learn=0.20.0
  - scikit-plot=0.3.7
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=38.4.0
  - simplegeneric=0.8.1
  - simplejson=3.16.1
  - sip=4.18
  - six=1.11.0
  - sortedcontainers=1.5.7
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tblib=1.3.2
  - tensorflow=1.0.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.9
  - toolz=0.8.2
  - traitlets=4.3.2
  - typing=3.6.4
  - uritemplate=3.0.0
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5
  - wheel=0.30.0
  - widgetsnbextension=3.1.0
  - xarray=0.10.0
  - xlrd=1.1.0
  - xlsxwriter=1.1.7
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.1
  - zict=0.1.3
  - zlib=1.2.11
  - pip:
    - adjusttext==0.7.3
    - anndata==0.6.19
    - decorator==4.4.0
    - jupyter-client==5.3.1
    - jupyterthemes==0.20.0
    - lesscpy==0.13.0
    - llvmlite==0.28.0
    - matplotlib==3.1.0
    - networkx==2.3
    - notebook==6.0.1
    - numba==0.43.1
    - numexpr==2.6.9
    - ply==3.11
    - prometheus-client==0.7.1
    - pyzmq==18.1.0
    - scanpy==1.4.3
    - send2trash==1.5.0
    - singlet==0.5
    - tables==3.5.1
    - tornado==6.0.3
    - tqdm==4.32.1
    - umap-learn==0.3.8
